A plataforma "WikiLeaks" entregou a vários jornais relatórios secretos da guerra no Afeganistão.
O site "Wikileaks" revelou cerca de 400 mil relatórios militares secretos relativos à guerra do Iraque.
Os documentos começaram a ser difundidos pela imprensa internacional.
O Pentágono pediu aos meios de comunicação social para não fazerem eco dos documentos divulgados pelo site.
A Amazon deixou de albergar o site da WikiLeaks.
As autoridades norte-americanas imputaram 22 crimes ao soldado Bradley Manning, apontado como principal informador do WikiLeaks.
Bradley Manning enfrenta Conselho de Guerra sob a acusação de ter fornecido ao WikiLeaks telegramas confidenciais, registos militares e um vídeo classificado.