José Saramago morreu aos 87 anos na sua residência da ilha espanhola de Lanzarote.
O Governo decidiu decretar dois dias de luto nacional.
A ministra da Cultura partiu para ir buscar o corpo do escritor a Lanzarote, em representação do Governo português.
O corpo de José Saramago vai ser velado no Salão Nobre da Câmara Municipal de Lisboa, saindo para Cemitério do Alto de São João, para ser cremado.
Milhares de pessoas acorreram ao cemitério, em Lisboa, para assistir à chegada do corpo de José Saramago.
Depois das cerimónias fúnebres, em Lisboa, as cinzas ficam em Portugal.