Os brasileiros vão decidir numa segunda volta quem será o sucessor de Lula da Silva na Presidência da República.
Dilma Rousseff recebeu 46,9 por cento dos votos e disputará a segunda volta com José Serra que obteve 32,6 por cento.
Será determinante o apoio de Marina Silva, do Partido Verde, que alcançou o terceiro lugar na primeira volta.
Dilma Rousseff foi eleita com 56 por cento dos votos e tornou-se a primeira mulher presidente do Brasil.
No discurso de vitória, emocionou-se quando agradeceu ao Presidente Lula da Silva.
José Serra do Partido da Social Democracia Brasileira obteve 43,95 por cento.
