Ai Weiwei, contestatário do regime comunista há anos, foi detido a 3 de Abril em Pequim, quando tentava embarcar para Hong Kong.
Este artista plástico, de 53 anos, foi detido no aeroporto de Pequim, quando se preparava para entrar num avião.
No mesmo dia, a polícia efectuou uma busca ao seu estúdio em Caochangdi, nordeste da capital chinesa.
Ai Weiwei continua detido em local desconhecido.
A detenção desencadeou vários protestos nas capitais ocidentais e nos meios culturais estrangeiros.
Ai Weiwei, libertado a 22 de Junho pelas autoridades chinesas, denunciou, através de Twitter, alegadas detenções ilegais e torturas de amigos.