Um atentado junto a uma igreja cristã ortodoxa copta fez pelo menos 21 mortos e mais de 70 feridos.
A explosão, não reivindicada, ocorreu por volta da meia noite e meia, altura em que os fiéis abandonavam a igreja dos Santos, em Alexandria, no Egipto.
Um suicida fez-se explodir.
Estavam mais de mil pessoas a assistir à missa de ano Novo.
A bomba rebentou no momento em que os fieis começaram a sair.
O Hamas condenou o atentado.
Sucedem-se manifestações de cristãos contra o atentado.
Nenhum grupo reivindicou a autoria do atentado.
As autoridades detiveram pelo menos 20 pessoas suspeitas.