Mais de 22,7 mil pessoas foram assassinadas no México desde 2006.
A "guerra de cartéis" pelo controlo do tráfico de droga fez 28 mil mortos durante a presidência de Felipe Calderon.
Um acerto de contas entre cartéis causou 35 mortos no estado de Guerrero, Sul do México.
Um comando armado sequestrou 22 turistas mexicanos na estação balnear de Acapulco.
As autoridades identificaram 18 corpos encontrados numa vala comum perto e são dos turistas sequestrados.
Cadávares de quatro homens foram descobertos numa estrada.
O cartel de La Familia actua em Guerrero, bem como em Michoacan, de onde eram estes turistas.
