Olegário Benquerença volta a figurar na lista dos árbitros do Mundial.
A selecção nacional empatou a zero com a Costa do Marfim.
A selecção de Portugal venceu por sete a zero frente à equipa de Coreia do Norte.
A selecção nacional e o Brasil empataram a zero.
A selecção portuguesa de futebol caiu nos oitavos de final do Mundial de 2010, ao perder por 1-0 com Espanha.
Termina o Mundial2010 com uma final entre a Holanda e a Espanha.
Espanha espera a chegada dos campeões do Mundial2010.
O Mundial de 2010 rendeu 7,98 milhões de euros à Federação Portuguesa de Futebol.