A "Primavera Árabe" irrompe de revoltas, que começaram a 17 de Dezembro de 2010, no Médio Oriente e Norte da África, contra regimes autoritários, que resultaram no derrube dos presidentes da Tunísia, Egipto e Líbia.
O Executivo de união nacional foi formado após a fuga de Ben Ali para a Arábia Saudita.
Nove meses após a rebelião que derrubou Ben Ali, sete milhões de tunisinos elegem uma Assembleia Constituinte.
Na Síria, pelo menos 24 pessoas foram mortas nas manifestações contra Bashar al-Assad.
Os reis de Marrocos e da Jordânia procuram responder às reivindicações populares com o anúncio de reformas constitucionais.