Os britânicos começaram a acampar junto à Abadia de Westminster, onde se vai realizar o casamento do príncipe William e de Catherine Middleton.
A cerimónia religiosa do casamento teve início cumprindo o horário estabelecido.
William e Kate Middleton lideraram o cortejo entre a abadia e o palácio.
O cortejo foi composto por mais quatro carruagens e acompanhado pela multidão.
No palácio de Buckingham teve lugar uma recepção oferecida pela rainha para 650 convidados.
O príncipe e a mulher vão passar o primeiro fim-de-semana enquanto casal no Reino Unido.
O casamento custou 282 mil euros aos pais da noiva.