Osama bin Laden, líder da organização terrorista Al Qaeda, foi abatido por forças especiais dos Estados Unidos durante uma operação terrestre a norte da capital do Paquistão.
Morreram pelo menos cinco pessoas no tiroteio.
O ADN retirado do corpo de uma das pessoas corresponde ao do líder da al-Qaeda.
Havia cerca de vinte pessoas na casa, algumas das quais foram feitas prisioneiras.
Os militares apoderaram-se do corpo do terrorista, que foi enviado para o porta-aviões norte-americano Carl Vinson, no Golfo Arábico.
Os Estados Unidos não informaram o Paquistão da operação porque o líder da al-Qaeda "poderia ter sido alertado".