Os ministros das Finanças da Zona Euro aprovaram o plano de resgate a Portugal.
O plano estabelece um empréstimo de 78 mil milhões de euros até Junho de 2013.
O FMI entra com 26 mil milhões de euros a uma taxa entre 3,25% e 4,25%.
Para impedir a bancarrota da Grécia, os líderes da Zona Euro aceitaram baixar os juros para 3,5 por cento a todos os que pediram ajuda.
O Estado Português já recebeu quase 20 mil milhões de euros, um quarto do pacote de ajuda.
A troika fez uma avaliação positiva à implementação das medidas por Portugal.