Sete anos e meio depois da chegada ao Iraque, a última brigada de combate norte-americana retirou-se, cumprindo a promessa do presidente Barack Obama.
As últimas tropas saíram do Iraque, restando agora 56 mil soldados que vão treinar o exército e polícia iraquianos.
A retirada americana é fruto de um acordo entre as autoridades dos EUA e do Iraque.
As atenções viram-se para os soldados que regressam mutilados ou com transtornos.
Aproximadamente 1.5 milhões de homens e mulheres serviram nos últimos sete anos.
A bandeira dos Estados Unidos foi retirada na cerimónia que marca o fim da presença norte-americana.