Mais de 250 mil eleitores são chamados a votar para as eleições da Madeira, de onde sairá novo Governo e nova Assembleia Legislativa.
Nove forças políticas apresentaram listas.
Além das sete com representação parlamentar - PSD, PS, CDU, CDS-PP, BE, MTP e PND - concorrem o PTP e o PAN.
O PSD está posicionado para nova vitória, correndo o risco de perder a maioria absoluta.
Até ao meio-dia votaram 23,47 por cento dos eleitores.
Até às 16h00 votaram 43,4 por cento.
O delegado da Comissão Nacional de Eleições recebeu queixas de irregularidades.
O cabeça-de-lista do PS reconheceu o resultado negativo.