José Sócrates insinuou que se demitirá caso o novo Programa de Estabilidade e Crescimento seja chumbado.
Passos Coelho explica as razões para que o PSD vote contra o PEC 4.
O PSD apresentou um projecto de resolução: Rejeitar o programa de Estabilidade e Crescimento apresentado pelo Governo.
José Sócrates pediu a demissão
O Presidente da República vai ouvir os partidos na sequência do pedido de demissão entregue pelo primeiro-ministro a seguir ao chumbo da oposição às medidas do PEC 4.
O primeiro-ministro justificou o pedido de demissão com a falta de diálogo político em que a oposição colocou o Governo.