O Comité Nobel atribuiu hoje o Nobel da paz 2011 a três mulheres: a Presidente da Libéria, Ellen Johnson-Sirleaf, a ativista liberiana Leymah Gbowee e a jornalista iemenita Tawakkul Karman.
Johnson Sirleaf, de 72 anos, economista, é a primeira mulher presidente de África eleita.
Leymah Gbowee organizou um grupo de mulheres para desafiar os senhores da guerra na Libéria.
Tawakul Karman, de 32 anos, é membro do partido islâmico Islah e liderou um grupo de defesa dos direitos humanos.
A Assembleia da República aprovou um voto de congratulação pela atribuição do prémio.
A União Europeia felicitou as três mulheres.