Um avião com 96 pessoas a bordo, entre os quais o Presidente da Polónia, despenhou-se no Oeste da Rússia quando tentava aterrar no aeroporto de Smolensk, 400 quilómetros a oeste de Moscovo.
Com o presidente Lech Kaczynski seguiam a mulher, os principais chefes militares, o governador do Banco Central, o chefe do Gabinete de Segurança Nacional e o chefe do Comité Olímpico do país.
As causas da queda do avião serão investigadas numa acção conjunta entre Rússia e Polónia.
Foi decretada uma semana de luto nacional.
Cem mil polacos encheram a principal praça da capital, Varsóvia, nas exéquias colectivas.