Um desmoronamento na mina de São José, a mais de 800 quilómetros de Santiago do Chile, deixa 33 mineiros presos.
Escavadora abre um poço de 75 centímetros de diâmetro e avança 20 metros por dia.
O poço permitirá trazer à superfície os mineiros retidos desde 5 de Agosto a mais de 700 metros de profundidade.
Uma "gaiola" para salvar os homens soterrados chegou às equipas de socorro.
69 dias depois, o primeiro mineiro chegou a terra.
Os mineiros foram trazidos à superfície um a um no interior da cápsula Fénix II.
O estado de saúde dos mineiros é satisfatório.
