O presidente da Apple apresentou o novo tablet.
Sem teclado físico, o iPad tem o mesmo sistema operativo do iPhone e ecrã táctil.
Não tem webcam, nem suporta cartões.
Com preços entre 500 e 830 dólares, deve ter o mesmo impacto que o iPhone nos telemóveis.
Uma das maiores limitações é que não suporta ambiente multitarefa.
Mais de um milhão de aplicações foram descarregadas no primeiro dia.
Estão a ser vendidos cerca de 200 mil aparelhos por semana.
Empresas portuguesas vão aproveitar para disponibilizar aplicações para dispositivos móveis.
O iPad chega a Portugal com preço entre 499 e 799 euros.