O cantor porto-riquenho Ricky Martin, 38 anos, admitiu que é homossexual num comunicado no seu site oficial.
Ricky Martin é pai de dois gémeos, de uma mãe de aluguer.
O irmão apoia a decisão de assumir a homossexualidade.
Depois de ter assumido o namoro com o gestor Carlos González, o cantor quer oficializar a relação.
O cantor pretende ter mais um filho.
Ricky Martin chegou à Argentina para promover o novo álbum "Música+Alma+Sexo" e para tratar dos papéis do casamento.
O concerto de Ricky Martin nas Honduras está a gerar protestos.
A Confraternidade Evangélica expressou desagrado ao ministro do Interior.