O parlamento da Catalunha proibiu corridas de touros naquela região de Espanha.
A partir de Janeiro de 2012, a Catalunha torna-se a segunda região a proibir as corridas de touros, depois das Canárias em 1991.
A interdição está circunscrita às touradas na praça Monumental de Barcelona e não abrangerá largadas de touros.
Com 68 votos a favor, 55 contra e nove abstenções, o parlamento catalão aprovou a iniciativa legislativa popular, proposta por 180 mil cidadãos.
Com a decisão, fica em aberto o futuro das corridas no resto do país.
O Governo de Zapatero mostrou-se contrário à proibição, mas respeita a decisão.