Duas explosões na zona comercial do centro de Estocolmo causaram um morto - o presumível bombista - e dois feridos.
Duas explosões no centro de Estocolmo fizeram um morto e dois feridos.
Um carro explodiu numa das ruas da capital e pouco depois outro rebentamento foi sentido perto do local.
Antes das explosões foram recebidas mensagens ameaçadoras, algumas em árabe.
Taymour Abdel Wahab é o presumível bombista suicida.
O bombista suicida é um cidadão sueco de 28 anos que viveu no Reino Unido.
A polícia britânica está a fazer buscas em Bedfordshire, numa operação relacionada com a explosão em Estocolmo.