Uma derrocada no Nordeste, nos Açores, fez com que um autocarro que transportava alunos de uma escola caísse numa ravina.
O veículo transportava três alunos da Escola Básica e Secundária do Nordeste, além do motorista.
Duas crianças foram transportadas para o centro de saúde local, uma com fractura na perna e outra com hipotermia.
O corpo do motorista foi encontrado junto aos destroços do veículo.
As autoridades encontraram o corpo da criança desaparecida na sequência do acidente com um autocarro numa ravina na ilha de São Miguel.
O cadáver estava debaixo de uma pedra, junto ao tejadilho do autocarro.