O presidente dos Estados Unidos evidenciou a importância da Cimeira da NATO em Lisboa para os aliados definirem posições sobre o processo de transição no Afeganistão.
A Aliança Atlântica não tem intenções de se tornar "polícia mundial".
A Aliança procura aumentar a cooperação com as Nações Unidas e União Europeia.
O conceito estratégico da Aliança Atlântica foi aprovado pelos 28 estados-membros.
A declaração final enumera conceito estratégico, defesa antimíssil ou evolução do conflito no Afeganistão, mas as novidades dizem respeito à despesa.
NATO e Rússia tentarão relançar a parceria estratégica.
A Rússia aceitou integrar o sistema de escudo anti-míssil da Aliança.
