Uma explosão isolou mais de 30 mineiros a cerca de 120 metros de profundidade.
A explosão ocorreu na mina de Pike River, na costa oeste da ilha do sul da Nova Zelândia.
Após a primeira explosão nenhum contacto foi estabelecido com os mineiros.
Os níveis de metano levaram ao adiamento da operação de resgate.
As autoridades insuflaram ar puro na mina.
Ao acidente conseguiram sobreviver dois mineiros.
Morreram os 29 mineiros que se encontravam soterrados.
Foram dados como mortos depois de uma segunda explosão.
As idades oscilam entre os 62 e os 17 anos.
Uma comissão irá investigar o acidente.