Na base do processo Freeport esteve o alegado financiamento de partidos políticos para alteração da Zona de Protecção Especial do Estuário do Tejo.
Tem como arguidos os ex-sócios da empresa Smith & Pedro, Charles Smith e Manuel Pedro, acusados de tentativa de extorsão.
O Ministério Público pediu absolvição dos dois arguidos, considerando que não ficaram provados os factos.
O Tribunal do Barreiro tinha, em julho, absolvido os dois arguidos, tendo extraído uma certidão para averiguar alegados pagamentos ilegais dentro do Ministério do Ambiente.
Os magistrados decidiram que não havia indícos que permitissem a reabertura do processo, pelo que foi arquivado.