O Organização Europeia para Pesquisa Nuclear (CERN) anunciou hoje que descobriu uma partícula nova que pode ser o bosão de Higgs.
O bosão de Higgs, teorizado há quase meio século pelo físico britânico Peter Higgs, era tão procurado porque, segundo o modelo padrão da física, é o responsável pela massa das outras partículas.
É a única partícula do modelo padrão que ainda não foi observada pelos cientistas.
Os investigadores anunciaram a descoberta do bosão de Higgs a 04 de julho.
A massa da nova partícula descoberta é de 125,3 GeV, cerca de 133 vezes a massa de um protão.
