Na segunda-feira completam-se 60 anos da ascensão da rainha Isabel II ao trono do Reino Unido, que celebrará o Jubileu de Diamante.
O domingo será o dia com acontecimentos mais populares, nomeadamente uma frota de mais de mil barcos no rio Tamisa, e festas nas ruas.
A Rainha foi hoje saudada por mais de 100.000 pessoas, no sul de Londres, dando início às comemorações.
A Rainha vai receber a realeza do mundo na celebração.
Esta tarde, a rainha e a família mais próxima saudaram uma multidão de 1,5 milhões de pessoas junto ao palácio de Buckingham.
