Milhões de pessoas foram afetadas, esta madrugada, pelo "pior apagão" dos últimos dez anos na Índia.
Pelo menos 300 milhões de pessoas ficaram sem eletricidade no norte da Índia, incluindo na capital Nova Deli.
Centenas de mineiros estavam  esta terça-feira retidos devido ao "apagão" que impediu o funcionamento dos elevadores das minas.
A Índia foi hoje novamente atingida por uma falha de energia.
O segundo "blackout" em dois dias deixou metade do país sem luz.
O fornecimento de energia elétrica na Índia foi plenamente restabelecido, esta quarta-feira.
No total, 20 Estados de um total de 29 foram afetados.
