O Curiosity aterrou com sucesso às 6h32 perto de uma montanha na Cratera de Gale, no hemisfério sul de Marte, tal como planeado.
É um robô da agência espacial norte-americana (NASA), de seis rodas, do tamanho de um carro.
Foi lançado no dia 26 de novembro de 2011.
O objetivo do robô é perceber se Marte alguma vez teve condições para a existência dos "ingredientes básicos da vida".
O engenho inclui câmaras de alta definição, um laser para estudar alvos até sete metros e um conjunto de instrumentos que analisarão o ambiente em busca de metano.
