Nova Iorque vai encerrar o metro e suspender os transportes públicos devido à aproximação do furacão Sandy.
O furacão poderá afetar até 60 milhões de pessoas.
A campanha eleitoral ficou suspensa.
O furacão "Sandy" vai atingir a costa noroeste dos EUA, com ventos poderosos, chuvas intensas e ondas.
O mau tempo provocado pelo furacão 'Sandy' obrigou ao fecho de um reator nuclear de New Jersey.
Barack Obama declarou estado de "grande catástrofe" no estado de Nova Iorque.
O estado de grande catástrofe foi decretado para Nova Jérsia.
Sobe para 85 o número de mortos nos Estados Unidos afetados pelo Sandy.