O meteorito que caiu a 15 de fevereiro perto da cidade russa de Tcheliabinsk é crucial para o estudo do sistema solar.
O peso do meteorito devia ser de várias toneladas.
A queda do meteorito atingiu seis cidades dos Montes Urais.
O ministério russo para as Situações de Emergência enviou para o local 20 mil homens.
1158 pessoas, das quais 289 crianças, ficaram feridas devido à queda do meteorito.
O peso do meteorito devia ser de várias toneladas
Os prejuízos materiais são de cerca de 25 milhões de euros.
Há registo de 1.200 feridos, sendo que 40 continuam hospitalizados.