Um meteorito, que os russos estimam que tivesse dez toneladas, desintegrou-se na sexta-feira de manhã perto da cidade de Tcheliabinsk.
A queda de pedaços do meteorito, que se partiu ao atravessar a atmosfera, provocaram prejuízos em muitos edifícios de seis cidades dos Urais, sobretudo vidros partidos.
Há registo de 1.200 feridos, sendo que 40 continuam hospitalizados.
Os prejuízos materiais são de cerca de um milhão de rublos.
A agência russa da energia atómica assegurou que as suas instalações na região não foram afetadas.
Após a queda iniciou-se uma caça aos fragmentos vindos do espaço.
