Em Bruxelas, o Eurogrupo aprovou um plano de resgate para Chipre no valor de 10 mil milhões de euros.
O Banco Central Europeu garantirá liquidez de urgência.
Sem esse dinheiro, os bancos cipriotas não aguentam mais de uma semana.
O parlamento cipriota aprovou o plano de resgate que prevê um empréstimo de 10 mil milhões de euros em troca de contrapartidas draconianas.
Parte do empréstimo provirá de uma tributação que pode atingir 60% nas contas superiores a 100 mil euros no Banco de Chipre.
O acordo garante que os depósitos inferiores a 100 mil euros não serão sujeitos a taxas.