Os cipriotas vão perder quase 10% das poupanças depositadas nos bancos de Chipre.
Chipre deverá garantir esse montante até segunda-feira para desbloquear o resgate de 10 mil milhões de euros.
Foi a condição imposta ontem pelos ministros da Economia e Finanças da Zona Euro.
Nove mil milhões provêm do Mecanismo Europeu de Estabilidade e mil milhões são do Fundo Monetário Internacional.
O governo de Chipre poderá sugerir uma taxa de 15% sobre os depósitos bancários superiores a 100 mil euros.
O acordo conseguido para Chipre garante que os depósitos inferiores a 100 mil euros não serão sujeitos a taxas.
