Um tribunal de Moscovo considerou que as jovens do grupo Pussy Riot são culpadas de «hooliganismo» e «incitação ao ódio religioso».
Nadezhda Tolokonnikova, 22 anos, Maria Alyokhina, 24, e Yekaterina Samutsevic, 30, entraram na Catedral do Cristo Salvador, em Moscovo, e cantaram uma canção onde pediam à Virgem Maria para livrar a Rússia de Vladimir Putin.
Foram condenadas a dois anos de prisão.
O Conselho Consultivo para os Direitos Humanos do Kremlin criticou a condenação.
O processo teve eco internacional e o julgamento foi criticado.
As jovens apresentaram recurso da sentença.
O Tribunal de Moscovo suspendeu a pena de Samutsevich.