O Costa Concordia naufragou na noite de 13 de janeiro de 2012, ao largo da ilha italiana de Giglio.
O cruzeiro que transportava 4.229 pessoas embateu em rochas a 300 metros da costa da Toscana.
Cerca de 3.200 eram turistas.
O disco rígido do navio foi encontrado, podendo fornecer dados sobre o acidente que fez 12 mortos.
As autoridades italianas reviram para 29 o número de desaparecidos.
O comandante Francesco Schettino encontra-se em prisão domiciliária.
Está a ser acusado de homicídio involuntário e abandono de navio.
Os passageiros que sobreviveram vão receber 11 mil euros de indemnização, mais reembolsos.