A Síria vive uma guerra civil, na sequência do movimento de contestação reprimido pelo regime.
O presidente sírio, Bashar al-Assad, deslocou tropas dos Montes Golã (junto a Israel) para Damasco e outras zonas.
O conflito entre forças do regime e oposição armada estendeu-se a Damasco.
A juntar ao número de sírios que procuram refúgio nos países vizinhos há mais de um milhão de pessoas deslocadas internamente.
Os Estados Unidos vão começar a armar rebeldes sírios.
A NATO pediu às autoridades para deixarem a ONU investigar denúncias.
A guerra civil já causou, desde março de 2011, mais de 90 mil mortos.