O treinador do Benfica assegurou que o jogadores estão motivados para a final da Liga Europa, apesar da derrota frente ao FC Porto que colocou o Benfica na segunda posição do campeonato.
O Benfica voltou a somar uma derrota, ao perder diante do Chelsea na final da Liga Europa.
Depois de ter deixado fugir o título de campeão nacional na penúltima jornada, e ter perdido a final da Liga Europa, Jorge Jesus viu os "dragões" conquistarem o campeonato.
O Vitória de Guimarães conquistou a Taça de Portugal, ao vencer o Benfica.
O clube lisboeta falhou a conquista dos três troféus.