A Federação Nacional de Professores recusou proposta do Ministério da Educação para adiar a mobilidade especial.
O dia da greve dos docentes coincide com o exame de Português e de Latim.
O Ministério da Educaçao entregou recurso por serviços mínimos para a greve.
O Governo não muda a data do exame e o ministro da Educação convocou todos os professores.
Os professores marcaram greve com objetivo de contestar a aplicação do regime de mobilidade especial por temerem despedimento e aumento do horário.
Os alunos do 12º ano que não conseguiram fazer exame de Português poderão fazê-la dia 2 de Julho.