Rafael Marques foi constituído arguido numa queixa-crime movida por nove generais e duas empresas angolanas, que o acusam de "calúnia e injúria".
A editora da Tinta da China foi constituída arguida na sequência da publicação do livro Diamantes de Sangue, do jornalista angolano Rafael Marques.
Na obra são denunciadas violações dos direitos humanos.
O Ministério Público arquivou o processo.
O Ministério Público concluiu que a publicação do livro se enquadra no exercício de um direito.
Depois de o Ministério Público ter arquivado a queixa-crime foram notificados de que foi contra eles "deduzida uma acusação particular" por parte dos generais.
