Um comboio de alta velocidade que fazia a ligação entre Madrid e Ferrol descarrilou, à entrada de Santiago de Compostela, cerca das 20.45 horas locais.
O comboio descarrilou ao fazer uma curva a 190 quilómetros por hora onde é proibido circular a mais de 80.
O acidente ferroviário que na quarta-feira causou pelo menos 80 mortos e 168 feridos terá sido originado por excesso de velocidade.
A Junta da Galiza decretou sete dias de luto oficial.
As autoridades espanholas concluíram a identificação de 67 das 80 vítimas mortais.
As peças do acidente estão à guarda da polícia na Corunha.