O Governo grego anunciou o encerramento da televisão e rádio pública, ERT, o que vai levar ao despedimento de 2.700 pessoas.
A Comissão Europeia não solicitou o encerramento.
Os sindicatos gregos apelam a uma greve.
Milhares de pessoas manifestaram-se contra o encerramento.
Vai ser criado um novo organismo de radiotelevisão.
O primeiro-ministro grego propôs a reabertura parcial da ERT.
Trabalhadores da ERT continuavam a ocupar a sede da emissora.
O tribunal sentenciou que a ERT deverá permanecer aberta até que se crie uma nova televisão pública.
O Conselho de Estado grego anulou a decisão do Governo de encerrar a ERT.