Um tornado devastou a cidade de Moore, no Oklahoma, Estados Unidos.
Morreram 24 pessoa e cerca de 240 ficaram feridas.
Duas escolas ficaram destruídas e estão a ser retirados os alunos.
Barack Obama prometeu auxílio.
O presidente da Câmara de Moore irá propor uma lei que determine a construção de abrigos em novas casas.
Mais de 100 pessoas foram resgatadas dos escombros.
Autoridades encerraram o aeroporto.
Vários tornados atingiram o estado norte-americano de Oklahoma deixando pelo menos cinco mortos e duas dezenas de feridos numa zona devastada por um tornado que matou 24 pessoas.
Três caçadores de tornados morreram.