Com críticas de presidentes de câmara e da Igreja, o projeto de lei que autoriza o casamento e a adoção a  homossexuais foi aprovado pelo Conselho de Ministros, devendo ser analisado no Parlamento.
De acordo com os trâmites do Parlamento francês, o texto deve ser aprovado pela duas câmaras.
Milhares de opositores desfilaram nas ruas.
O centro de Paris foi palco de incidentes.
A França tornou-se o 14 º país a legalizar o casamento entre pessoas do mesmo sexo.
A UMP anunciou que vai apresentar recurso.
Onze dias após a promulgação da lei, o primeiro casamento homossexual realiza-se em Montpellier.