O papa Bento XVI, 85 anos, anunciou a resignação, a partir do dia 28 de fevereiro, devido "à idade avançada".
Um novo papa será escolhido até à Páscoa.
A decisão sobre a data é da responsabilidade dos cardeais que se reunirão em congregações.
Bento XVI antecipou em 2010 motivos pelos quais um pontífice pode resignar ao cargo.
Bento XVI está quase cego do olho esquerdo e recebeu indicações médicas para limitar as viagens aéreas devido à tensão arterial alta.
O Papa Francisco visitou Bento XVI na residência de Castel Gandolfo.
Dois meses após a resignação, Bento XVI voltou ao Vaticano.