O papa Bento XVI, 85 anos, anunciou hoje a sua resignação, a partir do dia 28 de fevereiro, devido "à idade avançada".
Bento XVI está quase cego do olho esquerdo e recebeu indicações médicas para limitar as viagens aéreas devido à tensão arterial alta.
Um novo papa será escolhido até 31 de março.
A primeira mensagem em nome do papa Francisco I na rede social Twitter foi em latim: "Habemus papam franciscum".
O Papa Francisco entrou na Praça de São Pedro no papamóvel, antes de celebrar a missa inaugural do seu pontificado diante de centenas de milhares de pessoas.
