Cientistas da Organização Europeia para a Investigação Nuclear (CERN) anunciaram a descoberta de uma partícula que pode ser o bosão de Higgs.
O bosão de Higgs é uma partícula elementar que está prevista pelo modelo padrão da física de partículas.
É a única partícula do modelo que ainda não foi observada pelos cientistas, mas representa a chave para explicar a origem da massa das outras partículas elementares.
Foi teorizado na década de 60 do século passado pelo físico britânico Peter Higgs.
A massa da nova partícula descoberta é de 125,3 GeV, cerca de 133 vezes a massa de um protão.