O Jubileu de Diamante marca os 60 anos Isabel II no trono.
A data da efeméride é 6 de Fevereiro, o mesmo dia que em 1952 subiu ao trono devido à morte do pai, Jorge VI.
A data será simbólica.
As celebrações oficiais serão concentradas no primeiro fim-de-semana de junho em Londres, com um desfile de embarcações no rio Tamisa, festas populares e uma missa.
A Rainha Isabel II de Inglaterra vai receber a realeza do mundo inteiro na celebração dos 60 anos de trono.
A rainha iniciou uma digressão pelo Reino Unido para celebrar o Jubileu de Diamante.