O Euro2012 arranca a 8 de junho na Polónia e Ucrânia.
A Federação Dinamarquesa informou que os jogadores vão receber 400 mil euros caso vençam o Euro2012, no qual são adversários de Portugal.
A Alemanha, primeira adversária de Portugal, prometeu aos jogadores 300 mil euros caso conquistem o troféu.
Portugal está nos quartos-de-final.
A derrota contra Espanha pode ter sido dolorosa mas a Federação Portuguesa vai voltar com 15,5 milhões de euros.
A  UEFA tinha para distribuir 196 milhões de euros.
Andrés Iniesta foi eleito melhor futebolista.
A Seleção Nacional terminou com o "prémio" de equipa que mais faltas cometeu.