A UEFA tinha para distribuir no início do campeonato 196 milhões de euros.
A Federação vai voltar com mais 15,5 milhões de euros no bolso.
O espanhol Andrés Iniesta foi eleito o melhor futebolista do Euro 2012, numa lista de 23 que integra os portugueses Pepe, Cristiano Ronaldo e Fábio Coentrão.
Iniesta, jogador do Barcelona de 28 anos, foi o melhor em campo em três partidas - diante da Itália, frente à Irlanda e novamente na final contra a squadra azzurra.
A Seleção Nacional terminou o Euro'2012 com o "prémio" de ter sido a equipa que mais faltas cometeu.
