O WikiLeaks divulgou nos últimos anos milhares de documentos militares sobre o Iraque e o Afeganistão e de telegramas diplomáticos norte-americanos.
O fundador do Wikileaks está refugiado na embaixada do Equador em Londres desde 19 de junho.
O fundador do WikiLeaks, Julian Assange, infringiu medidas de coacção e será detido quando deixar a embaixada do Equador em Londres.
O Equador concedeu asilo político a Julian Assange.
Assange é alvo de um mandado de detenção europeu para responder a acusações de violação e agressão sexual.
Em Londres, o WikiLeaks lançou um apelo a manifestações em frente à embaixada do Equador.