O Governo do Equador decidiu conceder asilo ao fundador do portal WikiLeaks.
Julian Assange pode "ficar indefinidamente" na embaixada em Londres.
Está refugiado na embaixada do Equador desde 19 de junho, alegando que o processo na Suécia tem motivações políticas.
Se for extraditado para a Suécia, Assange diz correr o risco de nova extradição para os Estados Unidos para responder por espionagem, após a divulgação de 250 mil telegramas diplomáticos norte-americanos.
Nem o Reino Unido nem a Suécia deram garantias de que não será extraditado.
Cabe às autoridades norte-americanas dar garantias para evitar ser extraditado para os EUA.
