Mais de 200 milhões de norte-americanos vão a votos escolher entre um novo mandato do democrata Barack Obama ou a eleição do republicano Mitt Romney.
Barack Obama acusa Mitt Romney de propor o regresso à«política externa dos anos 1980».
O Presidente dos EUA, Barack Obama, votou em Chicago, Illinois, 12 dias antes da data oficial das eleições presidenciais e legislativas norte-americanas.
Segundo a última sondagem, os candidatos estão empatados com 49 por cento das intenções de voto.
As cadeias de televisão avançavam a reeleição de Barack Obama.
O Congresso norte-americano proclamou a vitória de Barack Obama nas eleições presidenciais.