Mais de 200 milhões de norte-americanos vão a votos escolher entre Barack Obama ou Mitt Romney.
Os dois candidatos estão empatados com 49 por cento das intenções de voto.
Pouco depois das 4h00, as cadeias de televisão avançavam a reeleição de Barack Obama.
O Congresso norte-americano proclamou oficialmente a vitória de Barack Obama nas eleições presidenciais, após a contagem dos votos.
O presidente reeleito afirmou que, «para os Estados Unidos da América, o melhor ainda está para vir».
Os presidentes da União Europeia e da Comissão Europeia dirigem "calorosas felicitações ao Presidente Obama pela sua reeleição".
