Centenas de milhões de pessoas ficaram sem energia eléctrica no norte e este da Índia.
O "apagão" paralisou o metro de Nova Deli, os transportes ferroviários e o funcionamento dos hospitais.
Centenas de mineiros estavam retidos devido ao "apagão".
A rede eléctrica falhou devido a sobrecarga.
A Índia foi novamente atingida por uma falha de energia que está a afetar cerca de metade dos habitantes.
O metro de Nova Deli voltou parar e os sinais de trânsito deixaram de funcionar.
O fornecimento de energia elétrica na Índia foi restabelecido.
20 Estados indianos de um total de 29 foram afetados.