A NASA fez chegar a Marte o veículo “Curiosity”.
O Curiosity deverá levar a cabo uma missão de dois anos.
É um robô de seis rodas, do tamanho de um carro.
O Curiosity foi lançado no dia 26 de novembro de 2011, tendo chegado à cratera Gale, na superfície de Marte.
Alimentado por um gerador nuclear, tentará descobrir se o ambiente marciano foi propício ao desenvolvimento da vida microbiana.
Desde agosto de 2012, data da aterragem, que a Curiosity capta imagens de alta resolução.
Seixos lisos e arredondados, encontrados pela sonda, são indício de que o Planeta Vermelho teve água à superfície.