Barack Obama declarou hoje o estado de "grande catástrofe" no estado de Nova Iorque na sequência da tempestade "Sandy", que inundou a baixa de Manhattan e deixou meio milhão sem electricidade.
Por causa do 'Sandy', a campanha eleitoral para as presidenciais norte-americanas ficou suspensa, a uma semana do escrutínio.
Pelo menos 37 pessoas morreram, quase sete mil continuam em centros de acolhimento.
O mau tempo obrigou ao fecho de um reator nuclear no estado de New Jersey, onde também um dique cedeu.
Três dias depois, mais de 600 mil continuam sem eletricidade, 200 mil no sul de Manhattan.
