Pelo menos duas pessoas morreram e 23 ficaram feridas nas duas explosões da Maratona de Boston.
As explosões colocaram Nova Iorque, Washington e Los Angeles em estado de alerta.
Nas duas explosões próximas da meta morreram 3 pessoas e ficaram feridas 264.
Tamerlan (26 anos) e Dzhokhar Tsarnaev (19) foram responsáveis pelo atentado a 15 de abril.
Tamerlan foi morto num tiroteio e Dzhokhar capturado.
Os irmãos de origem tchetchena são os principais suspeitos.
Dzhokhar Tsarnaev disse que o ataque foi liderado pelo irmão e que não houve grupos terroristas envolvidos.
Dzhokhar Tsarnaev pode enfrentar a pena de morte.