O músico Bernardo Sassetti morreu aos 41 anos.
O corpo foi encontrado pela Polícia Marítima, na zona do Abano, no Guincho.
As operações de resgate do corpo foram dificultadas pelo estado do mar.
O Ministério Público instaurou um inquérito à morte do pianista.
O Presidente da República, Aníbal Cavaco Silva, lamentou a morte do compositor e intérprete Bernardo Sassetti.
O Parlamento aprovou um voto de pesar.
Nascido em Lisboa a 24 de junho de 1970, Sassetti era bisneto de Sidónio Paes e sobrinho-neto do compositor Luís de Freitas Branco.
Casado com a atriz Beatriz Batarda, Sassetti tinha duas filhas.