O ministro das Finanças, Vítor Gaspar, apresentou o pedido de demissão e vai ser substituído pela secretária de Estado do Tesouro, Maria Luís Albuquerque.
Paulo Portas apresentou a sua demissão do Governo.
Escolha de Maria Luís Albuquerque para o Ministério das Finanças foi a gota de água.
Depois de Paulo Portas, todos os ministros e secretários de Estado do partido devem apresentar a demissão.
Pedro Passos Coelho garante que não se demite, que não aceitou a demissão de Paulo Portas e que quer esclarecer as condições de apoio político ao Governo de coligação.
Paulo Portas continua no Governo, como vice-primeiro-ministro.