O heptacampeão do Tour sempre reclamou inocência.
Os testemunhos de antigos companheiros apontam para recurso sistemático a eritropoietina, transfusões e testosterona.
Lance Armstrong reconheceu ter-se dopado, sem detalhar os métodos nem apontar os cúmplices.
O antigo ciclista norte-americano admitiu ter recorrido ao doping durante a Volta a França numa entrevista com Oprah Winfrey.
Foi a primeira entrevista desde que a União Ciclista Internacional decidiu retirar-lhe os títulos na Volta a França (1999-2005) e expulsá-lo do ciclismo.
O antigo ciclista norte-americano Lance Armstrong admitiu na segunda-feira ter recorrido ao doping durante a Volta a França  numa entrevista com Oprah Winfrey.