Os islamitas aproveitaram um golpe de Estado em Bamako para acelerar a tomada de controlo em todo o norte do Mali.
O Governo decretou estado de emergência em resposta à ofensiva por grupos rebeldes.
Intensificaram-se os combates entre o exército e os grupos islamitas, que tentam avançar em direção ao sul.
A França bloqueou a progressão dos islamitas.
Mais de 60 rebeldes islamitas foram mortos no norte do Mali, durante bombardeamentos das forças francesas.
Os radicais islâmicos abandonaram as cidades no norte do Mali, nomeadamente Gao e Timbuctu.
O número de refugiados em países vizinhos é de aproximadamente 150.000 pessoas.