O Facebook escolheu o Morgan Stanley para coordenar a oferta pública inicial (IPO).
O Facebook contratou o Deutsche Bank, o Crédit Suisse e o Citigroup para efectuarem a IPO, no valor de 5 mil milhões de dólares.
A empresa adiou a abertura do capital em bolsa.
A 18 de Maio as acções começavam a negociar em bolsa.
Rede Social está a cair e atingiu novo mínimo.
Os títulos atingiram o valor mais baixo nos 30,10 euros, o que compara com os 45 dólares no dia de estreia.
As receitas saíram melhores do que o esperado no segundo trimestre.