Mohamed Morsi foi declarado vencedor das eleições presidenciais no Egito.
As forças militares fizeram um ultimato ao presidente para que atenda às exigências do povo e partilhe o poder.
O golpe de Estado militar teve lugar depois de ter terminado o prazo do ultimato.
O exército depôs o primeiro Presidente eleito, há um ano no poder, depois de violentos protestos.
Os militares suspenderam a Constituição e dissolveram o parlamento.
Até às eleições, o presidente do Tribunal Constitucional, Adly Mansour, vai dirigir o Egípto.
Pelo menos 42 pessoas morreram e 300 ficaram feridas em confrontos entre polícia e apoiantes do presidente.