A contagem dos maias acabaria no solstício do Inverno, 21 de Dezembro de 2012.
Muitos arqueólogos concluíram que os maias não previram o fim do mundo, mas uma renovação.
Os investigadores alertam para estar a ser dado relevo a uma inscrição numa de cinco mil pedras.
Enquanto a NASA vai tentando explicar que o mundo não vai acabar, as casas de aposta vão rentabilizando o assunto.
As comunidades maias preparam-se para celebrar, a 21 de dezembro, o início de um novo ciclo.
A profecia maia está a ser levada demasiado a sério na Rússia.
Dimitri Medvédev veio pedir calma.