Os protestos começaram no início de junho, em São Paulo, contra a subida das tarifas dos transportes públicos, mas estenderam-se a outras cidades.
A repressão policial motivou outras pessoas a protestarem pela paz e pelo direito de manifestação, bem como outras queixas, entre quais corrupção e falta de transparência.
As manifestações criticam os gastos com eventos desportivos em detrimento de áreas como saúde e educação.
As autoridades de São Paulo revogaram o aumento nas tarifas.
Outras seis cidades brasileiras já haviam baixado as tarifas.
A ordem para baixarem o preço dos transportes partiu do antigo presidente Lula da Silva.