James Cameron tornou-se no primeiro homem a mergulhar sozinho até ao ponto mais profundo do planeta, a Fossa das Marianas (Oceano Pacífico), a 10 911 metros.
O cineasta chegou ao fundo do mar pouco antes das 23:00 de Lisboa e regressou à superfície cerca das 03:00 depois de ter recolhido imagens.
Cameron, de 57 anos, realizou a viagem num mini-submarino designado "Deepsea Challenger", fabricado pela sua equipa de engenheiros em colaboração com a National Geographic.
A fossa das Marianas, a quase 11 mil metros de profundidade, está situada perto da ilha de Guam, no sul do Pacífico.