O parlamento aprovou a 17 de maio (com 99 votos a favor, 94 contra e nove abstenções), na generalidade, um projeto de lei do PS para que os homossexuais possam co-adotar filhos adotivos ou biológicos da pessoa com quem estão casados ou com quem vivem em união de facto.
Votaram a favor as bancadas do BE, PCP, PEV, a maioria dos deputados do PS e 16 deputados do PSD.
O direito de co-adoção está restrito a pessoas com mais de 25 anos.
O bastonário da Ordem dos Advogados criticou o projeto de lei.
A Ordem dos Psicólogos aprova a co-adoção.